added improved handling for conda

diff --git a/install_shapepipe b/install_shapepipe
--- a/install_shapepipe
+++ b/install_shapepipe
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-LC_CTYPE=en_US.utf8
+export LC_ALL=en_US.UTF-8
+export LC_CTYPE=en_US.utf8
 
 ##############################################################################
 # Install ShapePipe Executables
@@ -177,8 +178,40 @@ build_mpi(){
 check_conda() {
   if ! type -t "conda" > /dev/null
   then
-    echo "Conda command not found, make sure it is installed before proceding."
-    exit
+    echo -ne "${RED}ERROR: Conda command not found, make sure it is installed before proceding.${NC}\n"
+    exit 1
+  fi
+  # Set Conda variables
+  CONDA_VERSION=$(conda -V | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/' )
+  CONDA_VERSION_MAJOR=$(cut -d'.' -f1 <<<$CONDA_VERSION)
+  CONDA_VERSION_MINOR=$(cut -d'.' -f2 <<<$CONDA_VERSION)
+  CONDA_VERSION_PATCH=$(cut -d'.' -f3 <<<$CONDA_VERSION)
+  CONDA_SH=/etc/profile.d/conda.sh
+  # Check Conda major version
+  if [ "$CONDA_VERSION_MAJOR" -lt 4 ]
+  then
+    echo -ne "${RED}ERROR: Found Conda version $CONDA_VERSION but require 4.0.0 or greater.${NC}\n"
+    exit 1
+  fi
+  # Check Conda minor version
+  if [ "$CONDA_VERSION_MINOR" -gt 4 ]
+  then
+    if [ -f "$CONDA_PREFIX_1$CONDA_SH" ]
+    then
+      source "$CONDA_PREFIX_1$CONDA_SH"
+    elif [ -f "$CONDA_PREFIX$CONDA_SH" ]
+    then
+      source "$CONDA_PREFIX$CONDA_SH"
+    else
+      echo -ne "${RED}ERROR: Could not find $CONDA_SH in \$CONDA_PREFIX.${NC}\n"
+      echo -ne "${RED}Activate the base/root Conda environment and try again.${NC}\n"
+      exit 1
+    fi
+    CONDA_ACTIVATE="conda activate"
+    CONDA_DEACTIVATE="conda deactivate"
+  else
+    CONDA_ACTIVATE="source activate"
+    CONDA_DEACTIVATE="source deactivate"
   fi
 }
 
@@ -201,7 +234,7 @@ check_binary2() {
     echo -ne "$2: ${GREEN}INSTALLED${NC}\n"
     if [ "$3" == TRUE ]
     then
-      "$CONDA_PREFIX/bin/$1" --version | head -n 1
+      "$CONDA_PREFIX/bin/$1" --version | head -n 2
     fi
   else
     if [ "$4" == TRUE ]
@@ -339,6 +372,7 @@ check_status () {
 # Function to show the installation setup
 setup() {
   check_status 'Operating System:' $SYSOS
+  check_status 'Conda Version:' $CONDA_VERSION
   check_status 'Build Conda Environment:' $BUILD_ENV $ENV_NAME
   check_status 'Install SExtractor:' $INSTALL_SEX
   check_status 'Install PSFEx:' $INSTALL_PSFEX
@@ -380,10 +414,13 @@ uninstall() {
 
 # Function to activate ShapePipe environment
 activate_shapepipe() {
-  conda activate $ENV_NAME || source activate $ENV_NAME || ( source $CONDA_PREFIX_1/etc/profile.d/conda.sh && conda activate $ENV_NAME )
+  # Run activation command
+  echo -ne "Running ${CYAN}$CONDA_ACTIVATE $ENV_NAME${NC}\n"
+  eval "$CONDA_ACTIVATE $ENV_NAME"
+  # Check if the activation was successful
   if [ "$?" -eq 0 ]
   then
-    echo -ne "Activating Conda environment ${CYAN}$CONDA_PREFIX${NC}\n"
+    echo -ne "Successfully activated ShapePipe environment ${CYAN}$CONDA_PREFIX${NC}\n"
     export LD_RUN_PATH=$CONDA_PREFIX/lib
   else
     echo -ne "${RED}ERROR: Could not activate ShapePipe environment.${NC}\n"
@@ -393,7 +430,8 @@ activate_shapepipe() {
 
 # Function to deactivate ShapePipe environment
 deactivate_shapepipe() {
-  conda deactivate || source deactivate || ( source $CONDA_PREFIX_1/etc/profile.d/conda.sh && conda deactivate )
+  # Run deactivation command
+  eval $CONDA_DEACTIVATE
 }
 
 # Build symbolic links for scripts
